# [functions]
#   node_bundler="esbuild"

[build]
  # command = "npm run build"
  publish = "dist"
  base ="/"
  functions="dist/functions"

[[redirects]]
  from="/*"
  to="/.netlify/functions/server/:splat"
  status=200