service: auth

plugins:
  - serverless-localstack
  # - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    host: http://localhost

package:
  patterns:
    - "!src/**"
    - "!.serverless/**"
    - "!volume/**"

useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  handler:
    handler: dist/functions/server.handler
    name: ${sls:stage}-handler
    url:
      cors: true
